# Text Representation

Text representation in NLP means converting text into a numerical form that a machine learning model can understand and process.

## What is Embedding?

Embeddings in NLP is a technique where individual words are represented as real-valued vectors and captures inter-word semantics.


In this notebook, We going to intreduce 2 techniques for embedding. These techniques will be used for a machine learning models such as SVM, Random forest, ... ect.

<img src="https://drive.google.com/uc?export=view&id=1jd0u_sGppDKqBYbhtJfGxp14lnUWUTTw" width="900">

# 1- TF-IDF

<img src="https://drive.google.com/uc?export=view&id=1saSt0mMgOQ2ybbTms1lu_ruhUcBWkKzL" width="500">

TF-IDF stands for term frequency-inverse document frequency. It is a measure that discounts common words. Used in the fields of information retrieval (IR) and machine learning, that can quantify the importance of words in a document amongst a collection of documents (also known as a corpus).

### Components of TF-IDF

1. **TF (Term Frequency):**  
   Measures how frequently a term appears in a document.


$$ \text{TF}(t, d) = \frac{\text{Number of times term } t \text{ appears in document } d}{\text{Total number of terms in document } d} $$


2. **IDF (Inverse Document Frequency):**  
   Measures how important a term is across all documents. Words that appear in many documents get lower scores.

$$    \text{IDF}(t) = \log \left(\frac{\text{Number of all documents N}}{\text{Number of documents containing the term } t}\right) $$

<img src="https://drive.google.com/uc?export=view&id=1JqPILC8TTh3yDQZCSuPNXwm6ER5YeJFh" width="900">

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [2]:
doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [3]:
tfidf = TfidfVectorizer()
result = tfidf.fit_transform(data) # returns sparce matrix

In [5]:
df = pd.DataFrame(result.toarray(), columns=tfidf.get_feature_names_out())
df

       data  digital  economy        is       new       of       oil      the
0  0.243777  0.34262  0.34262  0.243777  0.000000  0.34262  0.243777  0.68524
1  0.448321  0.00000  0.00000  0.448321  0.630099  0.00000  0.448321  0.00000

# Cosine similarity

In NLP, Cosine similarity is a metric used to measure how similar the documents are.


$$ \text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|} $$

Where:  
$ A \cdot B $  = dot product of vectors A and B  
$ \|A\| $ = magnitude (length) of vector A  
$ \|B\| $ =  magnitude (length) of vector B

#### Intuition

- If vectors point in the **same direction**, cosine similarity = **1** (maximum similarity).
- If vectors are **orthogonal (90° apart)**, cosine similarity = **0** (no similarity).

<img src="https://drive.google.com/uc?export=view&id=1b-o8CVfHBsjUGY_hXmxevU91gHidIuxO" width="900">

In [6]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [7]:
# Sample text data (replace with your own documents)

doc_1 = "Data is the oil of the digital economy"
doc_2 = "Data is a new oil"

data = [doc_1, doc_2]

In [8]:
tfidf_vectorizer = TfidfVectorizer() # Create a CountVectorizer instance
vector_matrix = tfidf_vectorizer.fit_transform(data) # Fit and transform the documents into numerical vectors

In [9]:
# Calculate the cosine similarity between the documents
cosine_similarity_matrix = cosine_similarity(vector_matrix)

df_cosine = pd.DataFrame(data=cosine_similarity_matrix, index=data, columns=data)

df_cosine

,Data is the oil of the digital economy,Data is a new oil
Data is the oil of the digital economy,1.000000,0.327871
Data is a new oil,0.327871,1.000000

# 2- What is Word2vec?

Word2Vec consists of models for generating word embedding. These models are two-layer neural networks having one input layer, one hidden layer, and one output layer.

Word2Vec utilizes two architectures :
1. CBOW (Continuous Bag of Words)
2. **Skip Gram**
<img src="https://drive.google.com/uc?export=view&id=1K38nEu_KhgtSJuG2RySwc6U5AAjVAgWZ" width="600">


Run this command in terminal to install
> pip install gensim

We will use fake and real news dataset to do our expirament. You can find the dataset here: https://www.kaggle.com/datasets/clmentbisaillon/fake-and-real-news-dataset?select=True.csv

In [10]:
import pandas as pd
import nltk
import numpy as np
import gensim

from nltk.tokenize import word_tokenize

In [14]:
df = pd.read_csv('content/True.csv', engine='python', on_bad_lines='skip') #fake-and-real-news-dataset-true.csv
df.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [15]:
tokens = []

for i in df['text']:
    token = word_tokenize(i)
    tokens.append(token)

In [16]:
w2v = gensim.models.Word2Vec(tokens, min_count=1, vector_size=100, window=5, sg=1)

In [17]:
print("Cosine similarity between 'provide' and 'program' - Skip Gram : ",w2v.wv.similarity('provide', 'program'))

Cosine similarity between 'provide' and 'program' - Skip Gram :  0.40091184

In [18]:
print("words that similar to 'program' - Skip Gram : ",w2v.wv.most_similar('program'))

words that similar to 'program' - Skip Gram :  [('programme', 0.8206329941749573), ('programs', 0.808307409286499), ('bond-buying', 0.7034410238265991), ('curbed', 0.6924551129341125), ('abolishing', 0.6818640828132629), ('modernization', 0.6789796948432922), ('programmes', 0.6772391200065613), ('restraints', 0.6772369742393494), ('entitlement', 0.6767295002937317), ('EB-5', 0.6731903553009033)]

# Tasks

### Task 1: Cosine Similarity
Use the Cosine Similarity method to determine how similar the following sentences are.

'This is the first document.',  
'This document is the second document.',  
'And this is the third one.',  
'Is this the first document?'

In [19]:
sen1 = "This is the first document."
sen2 = "This document is the second document."
sen3 = "And this is the third one."
sen4 = "Is this the first document?"

#Using Cosine Similarity to determine the similarity between the sentences
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([sen1, sen2, sen3, sen4])
cosine_sim = cosine_similarity(vectors)
print("Cosine similarity between the sentences:")
print(cosine_sim)

Cosine similarity between the sentences:
[[1.         0.64692568 0.30777187 1.        ]
 [0.64692568 1.         0.22523955 0.64692568]
 [0.30777187 0.22523955 1.         0.30777187]
 [1.         0.64692568 0.30777187 1.        ]]

### Task 2: TF-IDF
Use tf-idf method on the sentences below to determine the important words.

'data science is one of the most important fields of science',  
'this is one of the best data science courses',  
'data scientists analyze data'

In [20]:
sen1= "data science is one of the most important fields of science"
sen2= "this is one of the best data science courses"
sen3= "data scientests analyze data" 

#Using TF-IDF to determine the most important words in the sentences
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform([sen1, sen2, sen3])
print("TF-IDF vectors:")
print(vectors)

TF-IDF vectors:
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 21 stored elements and shape (3, 14)>
  Coords	Values
  (0, 3)	0.18952580966166682
  (0, 10)	0.4880979747364737
  (0, 6)	0.24404898736823685
  (0, 9)	0.24404898736823685
  (0, 8)	0.4880979747364737
  (0, 12)	0.24404898736823685
  (0, 7)	0.32089509027199203
  (0, 5)	0.32089509027199203
  (0, 4)	0.32089509027199203
  (1, 3)	0.2364200460658773
  (1, 10)	0.30443385488725433
  (1, 6)	0.30443385488725433
  (1, 9)	0.30443385488725433
  (1, 8)	0.30443385488725433
  (1, 12)	0.30443385488725433
  (1, 13)	0.40029393442429256
  (1, 1)	0.40029393442429256
  (1, 2)	0.40029393442429256
  (2, 3)	0.6410554491745127
  (2, 11)	0.5427006131762078
  (2, 0)	0.5427006131762078

The vectors show that the word: "data" is the most important by giving it the highest score.

## Word2vec

### Task 3:

Download the Simpsons dataset **(simpsons_script_lines.csv)** and apply the preprocessing procedure.  
Use the **'spoken_words'** column.
```
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text
```
Create a skip gram Word2Vec model as below.
```
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)

In [22]:
df = pd.read_csv('dataset/simpsons_script_lines.csv')
df.head()

        raw_character_text                                       spoken_words
0              Miss Hoover  No, actually, it was a little of both. Sometim...
1             Lisa Simpson                             Where's Mr. Bergstrom?
2              Miss Hoover  I don't know. Although I'd sure like to talk t...
3             Lisa Simpson                         That life is worth living.
4  Edna Krabappel-Flanders  The polls will be open from now until the end ...

In [23]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[0-9]", '', text)
    text = re.sub(r"[)(,”“.’$-]", '', text)
    return text

In [29]:
df['spoken_words_clean'] = df['spoken_words'].apply(
    lambda w: clean_text(str(w)) if pd.notna(w) else w)

df.head()

,raw_character_text,spoken_words,spoken_words_clean
0,Miss Hoover,"No, actually, it was a little of both. Sometim...",no actually it was a little of both sometimes ...
1,Lisa Simpson,Where's Mr. Bergstrom?,where's mr bergstrom?
2,Miss Hoover,I don't know. Although I'd sure like to talk t...,i don't know although i'd sure like to talk to...
3,Lisa Simpson,That life is worth living.,that life is worth living
4,Edna Krabappel-Flanders,The polls will be open from now until the end ...,the polls will be open from now until the end ...

In [33]:
tokens = []

for i in df['spoken_words_clean']:
    if pd.notna(i):
        token = word_tokenize(str(i))
        tokens.append(token)

In [46]:
Skip_gram_model = gensim.models.Word2Vec(tokens, min_count = 1, vector_size = 100, window = 5, sg = 1)
print(len(Skip_gram_model.wv.key_to_index))

44175

### Task 4

Use: wv.most_similar() method to :

1.	Find the words similar to “homer”.

2.	Find the words similar to “marge”.

3. Find the words similar to “bart”

In [40]:
#Results: 
print("words that similar to 'homer' - Skip Gram : ", Skip_gram_model.wv.most_similar('homer'))

words that similar to 'homer' - Skip Gram :  [('abe', 0.8824802041053772), ('marge', 0.8592597842216492), ('bartholomew', 0.8388531804084778), ('grampa', 0.8275673389434814), ('bart', 0.8256955146789551), ('allison', 0.8131957650184631), ('midge', 0.8083004951477051), ('mindy', 0.8073590993881226), ('sweetie', 0.8029881119728088), ('apu', 0.7988083958625793)]

In [41]:
print("words that similar to 'marge' - Skip Gram : ", Skip_gram_model.wv.most_similar('marge'))

words that similar to 'marge' - Skip Gram :  [('homer', 0.859259843826294), ('abe', 0.8533557057380676), ('sweetie', 0.8433542847633362), ('sweetheart', 0.8392242789268494), ('lisa', 0.8305422067642212), ('honey', 0.8287592530250549), ('becky', 0.8237810134887695), ('allison', 0.8219853639602661), ('midge', 0.8195794224739075), ('neddy', 0.8104878664016724)]

In [ ]:
print("words that similar to ' bart' - Skip Gram : ", Skip_gram_model.wv.most_similar('bart'))

words that similar to 'bart' - Skip Gram :  [('milhouse', 0.8788684010505676), ('lisa', 0.873477041721344), ('jessica', 0.8483780026435852), ('grampa', 0.844048023223877), ('sweetie', 0.8390275835990906), ('abe', 0.8381384611129761), ('saxophone', 0.8320063352584839), ('laddie', 0.8319055438041687), ('allison', 0.8260123133659363), ('maggie', 0.8259638547897339)]

### Task 5

Use the wv.doesnt_match() method to :

1.	Find which of 'jimbo', 'milhouse’, and 'kearney’ does not belong to the list.

3.	Find the odd one among "nelson", "bart", and "milhouse".

4.	Find the odd one among ‘homer', 'patty', and ‘selma'.

*Hint: You need to pass the strings as List*

In [47]:
#finding which of 'jimbo', 'milhouse', and 'kerney' does not belong to the list 
print("1. ", Skip_gram_model.wv.doesnt_match(['jimbo', 'milehouse', 'kearney']))
print("2. ", Skip_gram_model.wv.doesnt_match(['nelson', 'bart', 'milehouse']))
print("3. ", Skip_gram_model.wv.doesnt_match(['homer', 'patty', 'selma']))

1.  jimbo
2.  bart
3.  homer